"""initial tables

Revision ID: aee0d9a03b5b
Revises: 
Create Date: 2026-03-18 14:31:53.760254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aee0d9a03b5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_snapshots')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('idx_transactions_account_date'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_category'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_user_date'), table_name='transactions')
    op.drop_index(op.f('uq_transactions_file_signature'), table_name='transactions', postgresql_where='(hash_signature IS NOT NULL)')
    op.drop_table('transactions')
    op.drop_table('category_overrides')
    op.drop_table('account_detection_reviews')
    op.alter_column('bank_accounts', 'bank_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'account_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'nickname',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'account_number_last4',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bank_accounts', 'detected_account_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bank_accounts', 'account_fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'detection_source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('bank_accounts_user_id_account_fingerprint_key'), 'bank_accounts', type_='unique')
    op.create_unique_constraint('uq_user_account_fingerprint', 'bank_accounts', ['user_id', 'account_fingerprint'])
    op.alter_column('uploaded_files', 'original_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'storage_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'mime_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'checksum',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'detected_bank_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'detected_account_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'detected_account_last4',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'detected_fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('uploaded_files_user_id_checksum_key'), 'uploaded_files', type_='unique')
    op.create_unique_constraint('uq_user_file_checksum', 'uploaded_files', ['user_id', 'checksum'])
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_user_file_checksum', 'uploaded_files', type_='unique')
    op.create_unique_constraint(op.f('uploaded_files_user_id_checksum_key'), 'uploaded_files', ['user_id', 'checksum'], postgresql_nulls_not_distinct=False)
    op.alter_column('uploaded_files', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'detected_fingerprint',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'detected_account_last4',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'detected_account_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'detected_bank_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'checksum',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'mime_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_files', 'storage_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'original_filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_user_account_fingerprint', 'bank_accounts', type_='unique')
    op.create_unique_constraint(op.f('bank_accounts_user_id_account_fingerprint_key'), 'bank_accounts', ['user_id', 'account_fingerprint'], postgresql_nulls_not_distinct=False)
    op.alter_column('bank_accounts', 'detection_source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'account_fingerprint',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'detected_account_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bank_accounts', 'account_number_last4',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bank_accounts', 'nickname',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'account_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'bank_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('account_detection_reviews',
    sa.Column('review_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('proposed_bank_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proposed_account_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proposed_last4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proposed_fingerprint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('resolution_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resolved_account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("resolution_status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])", name=op.f('account_detection_reviews_resolution_status_check')),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.file_id'], name=op.f('account_detection_reviews_file_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_account_id'], ['bank_accounts.account_id'], name=op.f('account_detection_reviews_resolved_account_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('account_detection_reviews_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', name=op.f('account_detection_reviews_pkey'))
    )
    op.create_table('category_overrides',
    sa.Column('override_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('match_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('category_overrides_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('override_id', name=op.f('category_overrides_pkey')),
    sa.UniqueConstraint('user_id', 'match_text', name=op.f('category_overrides_user_id_match_text_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('normalized_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.TEXT(), server_default=sa.text("'USD'::text"), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bank_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hash_signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.account_id'], name=op.f('transactions_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.file_id'], name=op.f('transactions_file_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('transactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('uq_transactions_file_signature'), 'transactions', ['file_id', 'hash_signature'], unique=True, postgresql_where='(hash_signature IS NOT NULL)')
    op.create_index(op.f('idx_transactions_user_date'), 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index(op.f('idx_transactions_category'), 'transactions', ['user_id', 'category'], unique=False)
    op.create_index(op.f('idx_transactions_account_date'), 'transactions', ['account_id', 'transaction_date'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['queued'::text, 'running'::text, 'success'::text, 'error'::text])", name=op.f('processing_jobs_status_check')),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.file_id'], name=op.f('processing_jobs_file_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('processing_jobs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('processing_jobs_pkey'))
    )
    op.create_table('analysis_snapshots',
    sa.Column('snapshot_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('category_analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('analysis_snapshots_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('analysis_snapshots_pkey'))
    )
    # ### end Alembic commands ###
