"""add filename and file type nullable

Revision ID: b91e024a922a
Revises: 74c3709235b6
Create Date: 2026-03-19 06:26:24.769943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91e024a922a'
down_revision: Union[str, Sequence[str], None] = '74c3709235b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('processing_jobs', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'file_type')
    op.drop_column('processing_jobs', 'original_filename')
    # ### end Alembic commands ###
